spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucket.name=${AWS_BUCKET_NAME}

razorpay.key.id=${RAZORPAY_TEST}
razorpay.key.secret=${RAZORPAY_SECRET}
jwt.secret.key=${JWT_SECRET}